dubbo:
  application:
    name: shop_service
    registry:
      address: zookeeper://192.168.173.140:2181
server:
  port: 8888
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///shop
    driver-class-name: com.mysql.jdbc.Driver
    type: com.mchange.v2.c3p0.ComboPooledDataSource
mybatis:
  type-aliases-package: com.qn.shop.entity
  mapper-locations: classpath*:com/qn/shop/dao/mapper/*.xml