server:
  port: 8080
spring:
  thymeleaf:
    mode: HTML5
    cache: false
  mvc:
    static-path-pattern: "/static/**"
dubbo:
  application:
    name: shop_back
  registry:
    address: zookeeper://192.168.173.140:2181
  consumer:
    check: false
    timeout: 1000